<?php
var_dump(__DIR__ . '/../../');

$finder = PhpCsFixer\Finder::create()
    ->in(__DIR__ . '/../../')
    ->exclude('config')
    ->exclude('var')
    ->exclude('public/bundles')
    ->exclude('public/build')
    // exclude files generated by Symfony Flex recipes
    ->notPath('bin/console')
    ->notPath('public/index.php')
;

return (new PhpCsFixer\Config())
    ->setRiskyAllowed(true)
    ->setRules([
        '@Symfony' => true,
        '@Symfony:risky' => true,
        'linebreak_after_opening_tag' => true,
        'mb_str_functions' => true,
        'no_php4_constructor' => true,
        'no_unreachable_default_argument_value' => true,
        'no_useless_else' => true,
        'no_useless_return' => true,
        'php_unit_strict' => true,
        'phpdoc_order' => true,
        'strict_comparison' => true,
        'strict_param' => true,
        'blank_line_between_import_groups' => true,
        '@PhpCsFixer' => true,
        '@PHP71Migration' => true,
        '@PHP71Migration:risky' => true,
        '@PHP73Migration' => true,
        '@PHP74Migration' => true,
        '@PHP74Migration:risky' => true,
        '@PHP80Migration' => true,
        '@PHP80Migration:risky' => true,
        '@PSR12' => true,
        '@PSR12:risky' => true,
        'array_syntax' => ['syntax' => 'short'],
        'concat_space' => ['spacing' => 'one'],
        'comment_to_phpdoc' => true,
        'declare_strict_types' => true,
        // 'final_class' => true,
        'header_comment' => ['header' => ''],
        'heredoc_to_nowdoc' => true,
        'list_syntax' => ['syntax' => 'short'],
        'modernize_types_casting' => true,
        'native_function_invocation' => ['include' => ['@compiler_optimized'], 'scope' => 'namespaced'],
        'non_printable_character' => ['use_escape_sequences_in_strings' => true],
        'operator_linebreak' => ['only_booleans' => true, 'position' => 'end'],
        'ordered_class_elements' => true,
        'ordered_imports' => ['imports_order' => ['const', 'class', 'function']],
        'phpdoc_align' => ['align' => 'left'],
        'phpdoc_add_missing_param_annotation' => ['only_untyped' => true],
        'phpdoc_to_comment' => true,
        'phpdoc_types_order' => ['null_adjustment' => 'always_last'],
        'php_unit_test_class_requires_covers' => false,
        'protected_to_private' => true,
        'self_accessor' => true,
        'single_line_throw' => true,
        'types_spaces' => true,
        'yoda_style' => true,
    ])
    ->setFinder($finder)
    ->setCacheFile(__DIR__ . '/.php-cs-fixer.cache')
;
