api_platform:
    title: Symfony API
    description: 'Your amazing API which list and create any customer you want.'
    version: 1.0.0
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    show_webby: false
    formats:
        jsonld: ['application/ld+json']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
